# Generated by Django 4.2.28 on 2026-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(max_length=20)),
                ('stage', models.CharField(max_length=50)),
                ('progress', models.IntegerField(default=0)),
                ('transcription', models.TextField(blank=True)),
                ('video_url', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
