# Generated by Django 4.2.28 on 2026-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videojob',
            name='input_video',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='videojob',
            name='output_video',
            field=models.FileField(blank=True, null=True, upload_to='outputs/'),
        ),
    ]
